name: gendiff-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry==1.0.9
        make install
    - name: Run Tests
      run: |
        make test
    - name: Tests Coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 2fe77fc7587ea7d55c3d4d7348bdcfa6ce60707b0be5ebd0c67fe277f47791fa
      with:
        coverageCommand: make coverage
